### PR TITLE
Fix failing tests

### LINKED ISSUE #1440: Failing order-depend tests
@mzur I found some more tests that fail when I run them locally:

```
 FAILED  Biigle\Tests\Services\Reports\Volumes\ImageAnnotations\AbundanceReportGeneratorTest > init query annotation with multiple labels                                                       
  Failed asserting that 1120 is identical to 1119.

  at tests/php/Services/Reports/Volumes/ImageAnnotations/AbundanceReportGeneratorTest.php:1298
    1294▕         $results = $generator->initQuery(['images.filename', 'labels.id'])->get();
    1295▕         $this->assertCount(2, $results);
    1296▕         $this->assertSame($image->filename, $results[0]->filename);
    1297▕         $this->assertSame($image->filename, $results[1]->filename);
  ➜ 1298▕         $this->assertSame($al1->label_id, $results[0]->id);
    1299▕         $this->assertSame($al2->label_id, $results[1]->id);
    1300▕     }
    1301▕ 
    1302▕     public function testInitQueryAnnotationSession()

  1   tests/php/Services/Reports/Volumes/ImageAnnotations/AbundanceReportGeneratorTest.php:1298

  ──────────────────────────────────────────────────────────────────
   FAILED  Biigle\Tests\Services\Reports\Volumes\ImageAnnotations\AnnotationReportGeneratorTest > annotation session newest label                                                                 
  Failed asserting that 557 matches expected 555.

  at tests/php/Services/Reports/Volumes/ImageAnnotations/AnnotationReportGeneratorTest.php:496
    492▕         ]);
    493▕         $generator->setSource($session->volume);
    494▕         $results = $generator->initQuery(['image_annotation_labels.id'])->get();
    495▕         $this->assertCount(3, $results);
  ➜ 496▕         $this->assertEquals($al2->id, $results[0]->id);
    497▕         $this->assertEquals($al3->id, $results[1]->id);
    498▕         $this->assertEquals($al4->id, $results[2]->id);
    499▕     }
    500▕ 

  1   tests/php/Services/Reports/Volumes/ImageAnnotations/AnnotationReportGeneratorTest.php:496

  ──────────────────────────────────────────────────────────────────
   FAILED  Biigle\Tests\Services\Reports\Volumes\ImageAnnotations\AnnotationReportGeneratorTest > annotation session newest label separate label tree                                             
  Failed asserting that 1441 matches expected 1439.

  at tests/php/Services/Reports/Volumes/ImageAnnotations/AnnotationReportGeneratorTest.php:687
    683▕         ]);
    684▕         $generator->setSource($session->volume);
    685▕         $results = $generator->initQuery()->get();
    686▕         $this->assertCount(3, $results);
  ➜ 687▕         $this->assertEquals($al2->label->label_tree_id, $results[0]->label_tree_id);
    688▕         $this->assertEquals($al3->label->label_tree_id, $results[1]->label_tree_id);
    689▕         $this->assertEquals($al4->label->label_tree_id, $results[2]->label_tree_id);
    690▕     }
    691▕ 

  1   tests/php/Services/Reports/Volumes/ImageAnnotations/AnnotationReportGeneratorTest.php:687

  ──────────────────────────────────────────────────────────────────
   FAILED  Biigle\Tests\Services\Reports\Volumes\ImageAnnotations\AnnotationReportGeneratorTest > newest label separate label tree                                                                
  Failed asserting that 1474 matches expected 1472.

  at tests/php/Services/Reports/Volumes/ImageAnnotations/AnnotationReportGeneratorTest.php:1105
    1101▕         ]);
    1102▕         $generator->setSource($volume);
    1103▕         $results = $generator->initQuery()->get();
    1104▕         $this->assertCount(3, $results);
  ➜ 1105▕         $this->assertEquals($al2->label->label_tree_id, $results[0]->label_tree_id);
    1106▕         $this->assertEquals($al3->label->label_tree_id, $results[1]->label_tree_id);
    1107▕         $this->assertEquals($al4->label->label_tree_id, $results[2]->label_tree_id);
    1108▕     }
    1109▕ 

  1   tests/php/Services/Reports/Volumes/ImageAnnotations/AnnotationReportGeneratorTest.php:1105


  Tests:    4 failed, 5 skipped, 2164 passed (7861 assertions)
  Duration: 76.64s
```

Can probably be solved similarly to #1419 

And while at it, this here also requires fixing: https://github.com/biigle/core/actions/runs/24779722855/job/72507246714?pr=1426:

```
Biigle\Tests\Services\Reports\Volumes\VideoAnnotations\CsvReportGeneratorTest::testGenerateReportSeparateUsers
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_6::addFile('abc', '1138-jane-user.csv'). Either the method was unexpected or its arguments matched no expected argument list for this method
```

### PR DESCRIPTION
**Pull request by yannik131**
Closes #1440

### CODE REVIEW

**Comment by yannik131** [comment]
@mzur I struggled reading the tests because they all shared almost identical setup. I had to re-read this setup for every test to make sure that it is, in fact, identical, or where it's different if not. I checked duplication with [jscpd](https://github.com/kucherenko/jscpd) for `AnnotationReportGeneratorTest.php` and found that 70% of the 2000 lines is just duplicated code. I guess some duplication is usually tolerated in tests (see [this discussion](https://stackoverflow.com/questions/129693/is-duplicated-code-more-tolerable-in-unit-tests)), but 70% seems excessive. That's why I created a single fixture helper function that creates some data which is then re-used across the tests. I find it now much easier to read these test and understand what they actually do, since I only have to read the fixture once. What do you think? There's still more duplication left to refactor, but I'm not sure if it should be part of this PR. jscpd or other tools could also be applied to the project as a whole to find more copy-pasted sections.

**Comment by mzur** [comment]
As we just discussed you can improve tests if it's not too much effort. But the focus of our resources should be feature development and code quality of the application logic.

**Comment by yannik131** [comment]
@mzur  The `tests/php/Services/Reports/Volumes/ImageLabels/CsvReportGeneratorTest.php` has tests `testGenerateReportSeparateUsers` and `testGenerateReportSeparateLabelTrees`, both depend on users and label trees being returned by a query without an `ORDER BY` (see `CsvReportGenerator::generateReport`). A quick search across the project found 33 tests with the same name, many of which share the same logic bug (several were actually just copy-pasted). I fixed only the one that failed and will create a low-priority issue for the remaining tests. Without an `ORDER BY` these tests will also fail eventually.

File: tests/php/Services/Reports/Volumes/ImageLabels/CsvReportGeneratorTest.php [hunk 1]
```diff
@@ -275,14 +275,25 @@ public function testGenerateReportSeparateUsers()
...
+                    return false;
+                }
+            });
 
         $mock->shouldReceive('addFile')
             ->once()
-            ->with('def', "{$user2->id}-jane-user.csv");
+            ->withArgs(function ($source, $target) use (&$expectedTargets) {
+                return $source === 'def' && in_array($target, $expectedTargets);
+            });
```
[the remark this answers is not in the document]
Comment (yannik131) [reply tests/php/Services/Reports/Volumes/ImageLabels/CsvReportGeneratorTest.php:296]: The previous

```php
$mock->shouldReceive('getPath')
    ->twice()
    ->andReturn('abc', 'def');
``` 

guarantees that abc and def will be returned in that order, so the scenarios you described can never happen, because the return values of `getPath` are always used in this order in the implementation. This is hard to catch though since this whole test is very implementation-dependend.

File: tests/php/Services/Reports/Volumes/ImageLabels/CsvReportGeneratorTest.php [hunk 2]
```diff
@@ -275,14 +275,25 @@ public function testGenerateReportSeparateUsers()
...
+        
+        $expectedTargets = ["{$user1->id}-joe-jack-user.csv", "{$user2->id}-jane-user.csv"];
 
         $mock->shouldReceive('addFile')
             ->once()
-            ->with('abc', "{$user1->id}-joe-jack-user.csv");
+            ->withArgs(function ($source, $target) use (&$expectedTargets) {
+                if (($i = array_search($target, $expectedTargets)) !== false) {
+                    unset($expectedTargets[$i]);
+                    return $source === 'abc';
```
Comment (mzur) [inline tests/php/Services/Reports/Volumes/ImageLabels/CsvReportGeneratorTest.php]: Shouldn't this mutate only if the check is true?


```suggestion
                if ($source === 'abc' && ($i = array_search($target, $expectedTargets)) !== false) {
                    unset($expectedTargets[$i]);
                    return true;
```

Comment (yannik131) [reply tests/php/Services/Reports/Volumes/ImageLabels/CsvReportGeneratorTest.php]: The test will fail either way, but I guess this is slightly more expressive.

**Review by mzur — APPROVED** [review]
