### PR TITLE
Show warning for videos with invalid moov atom position

### LINKED ISSUE #983: Implement MP4 moov atom validation
If the moov atom is at the wrong location, [the video may not be displayed correctly](https://github.com/biigle/core/issues/391#issuecomment-1470201751). Add a validation step to the ProcessNewVideo job that checks the atom location. If the atom is at the wrong position, set an error state for the video (like "too large", "not found") and abort processing. Then display the error message in the UI.

Also create a manual page for how a video should be created/converted so it works with BIIGLE. The error message of the video should link to this page.

### PR DESCRIPTION
**Pull request by lehecht**
Show only warning for videos with a invalid moov atom position.

Closes #983.

### CODE REVIEW

File: resources/assets/js/videos/videoContainer.vue [hunk 1]
```diff
@@ -528,18 +529,24 @@ export default {
...
+                } else if (video.error === this.errors['codec']) {
+                    throw new VideoCodecError();
+                } else if (video.error === this.errors['malformed']) {
+                    throw new VideoMalformedError();
+                } else if (video.error === this.errors['too-large']) {
+                    throw new VideoTooLargeError();
+                } else if (video.size === null) {
+                    throw new VideoNotProcessedError();
+                }
             }
```
Comment (mzur) [inline resources/assets/js/videos/videoContainer.vue:550]: Why not add this as another `else if` and then set `this.invalidMoovAtomPosition = true` in the new block?

File: resources/views/videos/show/content.blade.php [hunk 2]
```diff
@@ -23,6 +23,14 @@
         </div>
     </div>
 </div>
+<message-curtain v-if="invalidMoovAtomPosition" v-cloak>
+    <div class="message-curtain--text text-danger">
+        <div class="lead">
+            Please <a href="/manual/tutorials/videos/fix-video-encoding">fix the video encoding</a>.<br>This may cause problems if you continue.
```
Comment (mzur) [inline resources/views/videos/show/content.blade.php:29]:
```suggestion
            The video file contains an invalid moov atom position. This can cause performance issues or incorrect annotation thumbnails in Largo. See <a href="/manual/tutorials/videos/fix-video-encoding">the manual</a> for how to fix this.
```

**Review by mzur — CHANGES_REQUESTED** [review]

**Review by mzur — APPROVED** [review]
Thanks!
