### PR TITLE
Fix xss vulnerabilites

### LINKED ISSUE #1117: Fix variable declarations in clone volume view
There are multiple issues with the JS variable declarations of the clone volume view: 

https://github.com/biigle/core/blob/8bd366ba0a53be5f5c97aec4a8fff4d0347ae2ef/resources/views/volumes/clone.blade.php#L7-L18

- Anything that returns a bool must be defined as `biigle.$declare('myVar', {{ $myBool ? 'true', 'false' }});`, otherwise it can result in incorrect JS syntax.

- User input (e.g. the volume name) must not be printed using `{!! !!}`. This could result incorrect JS syntax (e.g. if the volume name contains a `'`) or at worst in XSS attacks. In cases like these, `{{ }}` must always be used.

I will create a follow-up issue to check all views (also in modules) for XSS vulnerabilities.

### PR DESCRIPTION
**Pull request by lehecht**
Affected repos:

- [x] core
  - [x] resources/views/admin/index.blade.php
  - [x] resources/views/admin/announcements/create.blade.php
  - [x] resources/views/annotations/show.blade.php
  - [x] resources/views/annotations/show/tabs/labels.blade.php
  - [x] resources/views/auth/register.blade.php
  - [x] resources/views/export/index.blade.php
  - [x] resources/views/import/showLabelTree.blade.php
  - [x] resources/views/import/showUser.blade.php
  - [x] resources/views/import/showVolume.blade.php 
  - [x] resources/views/label-trees/merge/index.blade.php
  - [x] resources/views/label-trees/merge/show.blade.php
  - [x] resources/views/label-trees/show/base.blade.php
  - [x] resources/views/label-trees/show/labels.blade.php
  - [x] resources/views/label-trees/show/members.blade.php  
  - [x] resources/views/label-trees/show/projects.blade.php
  - [x] resources/views/label-trees/versions/show/labels.blade.php
  - [x] resources/views/label-trees/versions/show/base.blade.php
  - [x] resources/views/largo/annotationCatalog/show.blade.php
  - [x] resources/views/largo/project.blade.php
  - [x] resources/views/largo/show.blade.php
  - [x] resources/views/notifications/index.blade.php
  - [x] resources/views/partials/announcement.blade.php
  - [x] resources/views/partials/messages.blade.php
  - [x] resources/views/projects/partials/dashboardPreviewItem.blade.php
  - [x] resources/views/projects/show/base.blade.php
  - [x] resources/views/projects/show/label-trees.blade.php
  - [x] resources/views/projects/show/members.blade.php
  - [x] resources/views/projects/show/statistics.blade.php
  - [x] resources/views/projects/show/volumes.blade.php
  - [x] resources/views/projects/reports.blade.php
  - [x] resources/views/settings/notifications.blade.php
  - [x] resources/views/videos/show.blade.php
  - [x] resources/views/volumes/create/annotationLabels.blade.php
  - [x] resources/views/volumes/create/fileLabels.blade.php
  - [x] resources/views/volumes/create/labelMap.blade.php
  - [x] resources/views/volumes/create/step1.blade.php
  - [x] resources/views/volumes/create/step2.blade.php
  - [x] resources/views/volumes/create/userMap.blade.php
  - [x] resources/views/volumes/videos/index/meta.blade.php
  - [x] resources/views/volumes/partials/annotationSessionIndicator.blade.php 
  - [x] resources/views/volumes/edit.blade.php 
  - [x] resources/views/volumes/reports.blade.php
  - [x] resources/views/volumes/show.blade.php 
  - [x] resources/assets/js/core/components/typeaheadItem.vue
  - [x] resources/assets/js/label-trees/components/labelTypeaheadItem.vue
  - [x] resources/views/admin/announcements/create.blade.php
- [x] ananas
- [x] color-sort
- [x] geo
- [x] laserpointers
- [x] maia
- [x] user-storage
- [x] user-disks
- [x] module
- [x] newsletter

Potentially affected repos:
- [x] auth-lslogin
- [x] auth-nfdi
- [x] biigle.de
- [x] demo
- [x] denbi-service
- [x] ifdo
- [x] kpis
- [x] laravel-file-cache
- [x] magic-sam
- [x] metadata-coco
- [x] metadata-ifdo

Fixes #1117 and #1118.

### CODE REVIEW

File: resources/assets/js/core/components/typeahead.vue [hunk 1]
```diff
@@ -142,6 +142,21 @@ export default {
...
+                    '<': '&lt;',
+                    '>': '&gt;',
+                    '"': '&quot;',
+                    "'": '&#39;'
+                };
+                return escape[match];
+            };
+            escItem.name = escItem.name.replace(/[&<>"']/g, escape);
+            return escItem;
+        }
```
Comment (mzur) [inline resources/assets/js/core/components/typeahead.vue:159]: Please implement this as an `escapeHtml` function in `core/utils.js` so it can be reused in the future.

File: resources/views/volumes/clone.blade.php [hunk 2]
```diff
@@ -6,8 +6,8 @@
     <script type="module">
         biigle.$declare('destinationProjects', {!!$destinationProjects!!});
         biigle.$declare('volume', {!!$volume!!});
-        biigle.$declare('isImageVolume', {{$volume->isImageVolume()}});
-        biigle.$declare('name', '{!!old('name',$volume->name)!!}');
+        biigle.$declare('isImageVolume', {{ $volume->isImageVolume() ? 'true' : 'false' }});
+        biigle.$declare('name', {{ Js::from(old('name', $volume->name)) }});
```
Comment (mzur) [inline resources/views/volumes/clone.blade.php:10]: This should be enough, as `{{ }}` already escapes strings:

```suggestion
        biigle.$declare('name', '{{ old('name', $volume->name) }}');
```

File: resources/views/volumes/create/step2.blade.php [hunk 3]
```diff
@@ -4,9 +4,9 @@
 
 @push('scripts')
     <script type="module">
-        biigle.$declare('volumes.name', '{!! $oldName !!}');
+        biigle.$declare('volumes.name', {{ Js::from(old('name', $oldName)) }});
```
Comment (mzur) [inline resources/views/volumes/create/step2.blade.php:7]:
```suggestion
        biigle.$declare('volumes.name', {{ 'old('name', $oldName) }}');
```

File: resources/views/volumes/create/step2.blade.php [hunk 4]
```diff
@@ -4,9 +4,9 @@
...
         biigle.$declare('volumes.url', '{!! $oldUrl !!}');
-        biigle.$declare('volumes.handle', `{!! $oldHandle !!}`);
+        biigle.$declare('volumes.handle', {{ Js::from($oldHandle) }});
```
Comment (mzur) [inline resources/views/volumes/create/step2.blade.php:9]:
```suggestion
        biigle.$declare('volumes.handle', '{{ $oldHandle }}');
```

File: resources/views/volumes/clone.blade.php (hunk 2 above)
Comment (lehecht) [reply resources/views/volumes/clone.blade.php:10]: >So {!! Js::from($x) !!} breaks if $x contains a '? This sounds like a bug.

No, I mean when using `{!! old('name', $x) !!}` like before.

> But I'm fine with keeping the `{{ }}` if you think it is safer.

I mainly use the `{{ }}` to avoid errors and because I thought it would prevent xss attacks, but `{!! Js::from() !!}` also works. So then just use `{!! Js::from() !!}` ?

Comment (mzur) [reply resources/views/volumes/clone.blade.php:10]: Then let's sum up:
- Use `{{ }}` unless it breaks something or the value is an array/object
- Otherwise use `{!! !!}` for arrays/objects and make sure included user-input runs through `escapeHtml()` before it is shown with `v-html`
- Otherwise use `{!! Js::from() !!}` for non-arrays/objects

Correct?

Comment (lehecht) [reply resources/views/volumes/clone.blade.php:10]: Yes!

File: resources/assets/js/core/utils.js [hunk 5]
```diff
@@ -106,3 +106,19 @@ export let capitalize = function (s) {
 
   return s.charAt(0).toUpperCase() + s.slice(1)
 }
+
+export let escape = function (item) {
```
Comment (mzur) [inline resources/assets/js/core/utils.js:110]:
```suggestion
export let escapeHtml = function (item) {
```

File: resources/assets/js/core/components/typeahead.vue [hunk 6]
```diff
@@ -142,20 +142,8 @@ export default {
...
-                    '>': '&gt;',
-                    '"': '&quot;',
-                    "'": '&#39;'
-                };
-                return escape[match];
-            };
-            escItem.name = escItem.name.replace(/[&<>"']/g, escape);
-            return escItem;
+        escapeItem(item) {
+            return escape(item);
```
Comment (mzur) [inline resources/assets/js/core/components/typeahead.vue:146]:
```suggestion
            return escapeHtml(item);
```

File: resources/assets/js/core/components/typeahead.vue [hunk 7]
```diff
@@ -42,7 +42,7 @@
 
 <script>
 import TypeaheadItem from './typeaheadItem.vue';
-import {debounce} from '../utils.js';
+import {debounce, escape} from '../utils.js';
```
Comment (mzur) [inline resources/assets/js/core/components/typeahead.vue:45]:
```suggestion
import {debounce, escapeHtml} from '../utils.js';
```
